server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      filters: stat,wall,slf4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    dynamic:
      datasource:
        # MySQL
        master:
          url: jdbc:mysql://localhost:3306/aiops_db?useUnicode=true&&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: AIops_Admin
          password: AIops_Admin
        # Neo4j
        neo4j:
          url: jdbc:neo4j:bolt://localhost:7687/neo4j
          driver-class-name: org.neo4j.jdbc.Driver
          username: neo4j
          password: neo4j123
#          #  Encounter Error but Okay
#          druid:
#            test-while-idle: false
#            validation-query: MATCH(n) RETURN n
  neo4j:
    url: bolt://localhost:7687/neo4j
    authentication:
      username: neo4j
      password: neo4j123
  elasticsearch:
    uris: 82.157.145.14:9200
  # jpa:
  #   show-sql: true
  #   hibernate:
  #     ddl-auto: none

mybatis-plus:  # if mybatis, change this
  mapper-locations: classpath:/mapping/**/*.xml
  type-aliases-package: com.aiops_web.entity
  # Only for mybatis-plus
#  configuration:
#    map-underscore-to-camel-case: false

jsch:
  username: serveradmin/root
  ip: 10.60.38.173
  port: 50022
  password: Tongji409!
  StrictHostKeyChecking: 'no'
